### PR TITLE
Player direction

### PR DESCRIPTION
**Pull request by parkerhams**
Hey David - I've adjusted the move drag value to be 1.3, and thrust to be 15. I've removed the rotation drag variable. I've found this value of 1.3 gives a slight feeling of inertia if you rotates a full 360 degrees after reaching max acceleration, but you begin moving in the opposite direction in about a second or so.

I'd be interested to see how you think this feeling when moving, since I may be viewing it too closely. Let me know your thoughts!

### CODE REVIEW

**Review by dantogno — COMMENTED** [review]
It's definitely better. We can merge it if you're happy with it (let me know). Stopping is more responsive than changing direction. Should they feel similar? Personally, I would make turning / changing direction as responsive as stopping.

**Comment by dantogno** [comment]
Oh yeah, don't forget to get in the habit of mentioning what issue your PR is addressing in the PR description like this #8 :)

**Comment by parkerhams** [comment]
Hey David - just made another commit playing with those values further, and I've tried to make the stop and the turn feel like there's momentum and inertia while still feeling precise, so I adjust the movingDrag and stoppingDrag and slightly tweaked the camera follow value to make it a more noticeable zoom in once the player stops moving. Let me know if this feels to loose or imprecise to you! Then we can up the values. #8

**Comment by dantogno** [comment]
@parkerhams Regarding tagging the issues, I just want you to tag the issue when you first open a PR that is related to an issue. Or if you are directly referring to one.

**Review by dantogno — APPROVED** [review]
This feels great now, good work!

**Pull request merged**
