### PR TITLE
Asset import merged to master to start using models

### PR DESCRIPTION
**Pull request by parkerhams**
*Says it can't automatically merge... will that cause an issue?

### CODE REVIEW

**Comment by dantogno** [comment]
@parkerhams The meta file probably got a conflict because as you switch branches, it deletes files that aren't in the new branch but were in the old one. But it doesn't remove the empty folders. So Unity then generates new meta files for those folders (because it removed the .meta files from the branch that had files in those folders when you switched branches).

This is confusing and annoying, I know. The only "solution" I know of for avoiding this is to be very careful about what you commit, and not commit meta files that are not related to the branch / changes you are making in your commits.

**Comment by dantogno** [comment]
In this case, it's probably safe to just resolve the conflict using the meta file from this PR (not master), since master shouldn't have known about the files in this PR yet anyway.

**Comment by dantogno** [comment]
@parkerhams So I switched to this branch and chose  **Branch > Update from master** in GitHub Desktop and it seems to have automatically fixed the conflict / merge. I will go ahead and merge the PR now.

**Comment by parkerhams** [comment]
Thanks David - I'll be careful and I'll be mindful of those meta files so as not to cause any issues. Good thing to note, appreciate it! Hopefully this will make your job easier going forward.

**Pull request merged**
